apiVersion: v1
kind: Secret
metadata:
  name: qlever-secrets
type: Opaque
data:
  QLEVER_UI_USER: ENC[AES256_GCM,data:/90TAG6umxA=,iv:f6E/r7Kg/awePcvGScK8fUurj0JOOr46+w0X61cbUyI=,tag:SbS4k49BM0JzoloW/ny22g==,type:str]
  QLEVER_UI_PASSWORD: ENC[AES256_GCM,data:4sCV22ybQNaFtxuE1A9JassC+YOR7BN+SU9c/A==,iv:PI0P32Z4Zi4zxGwS/pzTJkyWwzGyIegw+3sTHiRoJ6o=,tag:F7EFZ9e2HceppeNGkM1whw==,type:str]
  TOKEN: ENC[AES256_GCM,data:mOanduGP/oDuD1FOFvZGw7XamNdIYTbLUBBSsGZdYJ151mK6qqpD6nB8av9prD5ln1TrNHxRP3TxyvUKoZFfygZjXDC4M1++HK6IfziGh/Lqnbru85ehAg==,iv:MNswLpQ71PbLd9ziKYRfvI7TlLrZyzyDezm8moGjByY=,tag:to6Jm0BPzVrubBbh0nuuFw==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T05:31:25Z"
  mac: ENC[AES256_GCM,data:VBrykjzpg+In18DzuD2HKKecWmtHAfXMi4ofJXZmb1Aok5qENOgmsNrQT68VOikT+2DjtenDQfoVLjBq+WiW56eDHSq+RfKuSTkbEZKPLModc7WxKRw/x2ghovorSvek8ruyexN+YZlZ3T0GBndqWQ/2JOmksWQStAtM6xdpgzY=,iv:zO/MfnvbXAikUYlOVD/1P54teQ5+PLkrUIJXfzSYh2k=,tag:hBjyuGo1We0Nc79RSgntIA==,type:str]
  pgp:
    - created_at: "2026-08-11T05:31:25Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ/+Mx6L6h5N9IXFyuN/4f9hVk3DUdc5U/etjw0x7IWT1RTE
        wbw74sL2Ag1O3nsIWmKvIMbYW0rhZs+N8Dweoihxxukbs7h7hCQeE9DT0JM9S2kf
        kmRNAj+NssJGzu3r7KZTsQmrVIwldc8INl0jE7J5w324vCfUzLrXsI6JsAlwGzPH
        cqV2HeyRS1iImUw5jx2Xc7RXvTSDOJy9eHbhEjCKsrgNZg5ytIT0eeVvoxJxjduo
        MuDE/xQiImb3XX88cxlKrIWyBo2kPwWcMoVDyyQOQpdQvMIihOGBA7d+QOdfdYq4
        mVM7CZiuENZwIMaYMZzE1YBDKf3ndeOzwMG+pK3vjQFou5+cgR9iHFuKe4lGLE9a
        Akno0IgkQG2HboUpR5BfL+jkun2/2X+Ocf1/121KBXTgcv3xom1Xg4yjCxnYWMe1
        YZ/tOvsToStzbx7fcbrHOqLWhHbIFkW1vOh+l52xwRjwVXRxmHIi2uTxi1+bNkF/
        9S2vpBOyvQGxvR9A3Z4bdFQN/88QG3Rcb3RG/KkXz1BnRsE0LR06+7YJ2RHIXEww
        7wP3GEvaZC0YIv6cQjzgc6XGeCDr5zZp91LQLCTQ+Fk/yNjYn+nea/St1VsyYvAb
        O7m5HxohoCTd5n4e3TuR73jlasEVNY68JJGn2rSgmN5w5WrtiPrEifFOvO4VZv7S
        XAGNKRUv8/n8y9uxFDkfJTORmFy2Cr6qIBXSXazz0QH/Wc/gEMZoWtNHCHlLPMDZ
        FR2b4Bz+KEfd8eXvELrNB6QlS7oZ0X8oiGedb5iLfRJmiLUJb/bEbai3b6O+
        =0lIf
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  version: 3.13.3
