apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.mediawiki.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        kubectl.kubernetes.io/default-container: "mediawiki"
    spec:
      securityContext:
        fsGroup: 33 # www-data
      initContainers:
        - name: copy-static-files
          image: "{{ .Values.mediawiki.image.repository }}:{{ .Values.mediawiki.image.tag }}"
          command:
            - sh
            - -c
            - |
              cp -r /var/www/html/w/skins /static/skins
              cp -r /var/www/html/w/resources /static/resources
              cp -r /var/www/html/w/extensions /static/extensions
              cp -r /var/www/html/w/images_repo /static/images_repo
              cp /var/www/html/w/robots.txt /static/robots.txt
          volumeMounts:
            - name: static-files
              mountPath: /static
      containers:
        - name: apache
          image: "{{ .Values.apache.image.repository }}:{{ .Values.apache.image.tag }}"
          imagePullPolicy: {{ .Values.apache.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.apache.resources.requests.cpu }}
              memory: {{ .Values.apache.resources.requests.memory }}
            limits:
              cpu: {{ .Values.apache.resources.limits.cpu }}
              memory: {{ .Values.apache.resources.limits.memory }}
          ports:
            - containerPort: 80
          env:
            - name: WIKIBASE_HOST
              value: "127.0.0.1"
          volumeMounts:
            - name: static-files
              mountPath: /var/www/html/w/skins
              subPath: skins
            - name: static-files
              mountPath: /var/www/html/w/resources
              subPath: resources
            - name: static-files
              mountPath: /var/www/html/w/extensions
              subPath: extensions
            - name: static-files
              mountPath: /var/www/html/w/images_repo
              subPath: images_repo
            - name: static-files
              mountPath: /var/www/html/w/robots.txt
              subPath: robots.txt
          startupProbe:
            httpGet:
              path: /w/api.php?action=query&meta=siteinfo&format=json
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /w/api.php?action=query&meta=siteinfo&format=json
              port: 80
            periodSeconds: 10
        - name: mediawiki
          image: "{{ .Values.mediawiki.image.repository }}:{{ .Values.mediawiki.image.tag }}"
          imagePullPolicy: {{ .Values.mediawiki.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.mediawiki.resources.requests.cpu }}
              memory: {{ .Values.mediawiki.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mediawiki.resources.limits.cpu }}
              memory: {{ .Values.mediawiki.resources.limits.memory }}
          ports:
            - containerPort: {{ .Values.mediawiki.port }}
          volumeMounts:
            {{- include "mediawiki.volumeMounts" . | nindent 12 }}
          env:
            {{- include "mediawiki.env" . | nindent 12 }}
            {{- include "mediawiki.phpfpmEnv" .Values.mediawiki.phpfpm | nindent 12 }}
          envFrom:
            {{- include "mediawiki.envFrom" . | nindent 12 }}
      volumes:
        - name: static-files
          emptyDir: {}
        {{- include "mediawiki.volumes" . | nindent 8 }}