apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/mscexplainer

patches:
  - path: values-production.yaml
    target:
      kind: HelmRelease
      name: mscexplainer
