apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ipfs
  - secrets.yaml
  - admins/ff1bbde59436c6bd.yaml
  - admins/1bd79c9e9959c189.yaml

patches:
  - path: values-production.yaml
    target:
      kind: HelmRelease
      name: ipfs
