apiVersion: v1
kind: Secret
metadata:
  name: ipfs-oauth2-proxy
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:/b+1KdIqD0VQtZcHYlkfyz8b+whrEQnLlaBElIz/TiM6VcG2adquclBsb3Duz3IZxKUVi3rshOegWJzVcVgR9O1zEC//aVEV,iv:OLulGENOHKudbGR+VEfCpozmont5ScTKJoLmS4RsNTs=,tag:Pml2rXdLPn7lLXsw/GdL5Q==,type:str]
  OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:uHmsE48SKmesDtJky4x8pWnqbzTRWTb8adJjM4E800P4iY8=,iv:HvNUx52JWs2tIkqkWb8NF74O9sfRof4KhMRwt1lsZuk=,tag:vJxAxoVzgYzJlkzfIOQpbg==,type:str]
  OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:B9hPTuD/wE+eMnwAXJBmHZDfSEtlxlX0aOfaxUHOglSsv9S/8HAAes/KhJI=,iv:rMhjwR+IN35pRfZB6HF6bpXT+pLXy3/voofzMlgLGSQ=,tag:zrG6W2Zb/ibO6DNhStaOnA==,type:str]
  allowed-emails: ENC[AES256_GCM,data:Ll6EYB2Nq06tIAvfP6HCYB6v,iv:+CtIqNOmNgykhXmrKo8Dns+m7z5zuxjBJJ0YW8DczvQ=,tag:LTBi6rkC7h22G82JoQ1V9A==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T08:17:24Z"
  mac: ENC[AES256_GCM,data:Mn6ByPvw2eXEGaEs9WxCnSq7/c78rKneFYaX8BHGnG7ratVMpSXLXgulKUKM341olbdSdO4gnj2XbyPOop8XZ5DOcWoX1fRe9ZUxtp9Wy+BjX4fE/yBSFfYcpE8HyeIYwCpijGqkbjbmWYVIHXQphdEQwITlFMARQU36vPhI1/0=,iv:bs0pyyz0MAdUK9ivvvvfYT6znGEfmLb8PRsCqTbdloY=,tag:oA9JadrtQ06LBp9+Myf9iQ==,type:str]
  pgp:
    - created_at: "2026-09-01T08:17:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ//Quo5hTzdAZPHqhWnob6F2J46+sTg1AZ12WthiKfaVciT
        l0Gc3e/3qbrAxMF7MxyOv2L4XTsokKBFQfAP4ZG3XkN2O7UQHw+S1v0rpXZmFhyp
        MAtO0F0W5FBUbxgjNBvfOcnKQESjGJvGTLeLJ+OJumgjFR252vYn+g3eGYXoh1+o
        zBHI8vEhVnRs2itJDP7MvIysB4f+HWaoVuovlIPAeuxp8pUml/3zvrJJxzq8DmYt
        WjXqghf9b2TRkftv3AGOalXvH2HdL94yPUQ6s4dywa96k2ukeGDk6jDlxU3W9zoP
        eiDLmaDHfxS2pNzq1FUYhLre1UCpSS8lIM4mvcDplpYcAtf/KRV765EDAWxP9imb
        poXGw+U4AcmpDef3G+Dvl9T6Lyjd2Op/P0IeOekqja3/x5LD3kIl2GGcTfzpc8r/
        27sWzfYSEOEZ46F1q/g+wwe9xq14C4h0KWxDUwIzKb2nLVAhuOgsKyO8A6WUgQf4
        /xBawUB21uGyMSbaMbw/19pVdKQoqB+Ho38Fsxv5oDvqxXqCud8470A4Am/Wz8+9
        GM5RVCbtJ6VlpFCJ8egySxlyXmi1jFFQ+U43sUP/GN8aeT+ApIbEe32djIcvJWEq
        oA8jdX53H0ZPIMxplCspgwVH+TnswmzkKtL8LJU6Ypk3mpX3+DVdnKViFssGQ77U
        aAEJAhAKxXMW/RenvzfxCHJ/QF/k12jrG70FiHSvspHdgBldftPr8CUxtI3O4ZFw
        1Gp0yZhRxVHCTjRPsOS4zgqonfBZj3GwlUY53N1Jcb6YjpWQ2fKv32W3M98RmGdr
        N5lvDjCIc5gg
        =y0iT
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  version: 3.13.3
