apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ipfs
spec:
  chart:
    spec:
      version: "0.2.2"
  values:
    admin:
      enabled: true
      existingSecret: ipfs-oauth2-proxy
      allowedEmailSecrets:
        - ipfs-oauth2-email-ff1bbde59436c6bd
        - ipfs-oauth2-email-1bd79c9e9959c189
      secretRevision: "20260901113746"
