apiVersion: v1
kind: Secret
metadata:
  name: anubis-key
type: Opaque
data:
  ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:ja1uj84BmNeOF8s+s7QujSctz2Oj18ny5F5VNlWzOork6aAMaSnTtYpSFF2Y5+UGB6choBDFUrTw57Z9WZmNGfL2EBF6odWeB1o6cq/izuJ8ArRVQHfgdg==,iv:cI9Q478cnTzH/NbQKU7ThkEhgvfKX7kayJvCI/ZdT3w=,tag:ZkxgG9gvvuMXGf8/GMa7sA==,type:str]
sops:
  lastmodified: "2026-04-29T13:18:15Z"
  mac: ENC[AES256_GCM,data:Ah31loURVMwHKBbzc6ynQoPFkoafTqX2iaI2XH/tXFlrVZDd8k8dP2XEAxDrU7bSRaBdPHDjcMO0Mqngdt3YMW729ZSninaG4lNKhqHINK3Ljd4LCrKg9YgiPBUNAqQRohlzS5yCBzlkHkamKo0MNQ1ac/t3kbK1XDFQAMIis3k=,iv:s0bxEqFgqmWDsbAUYIms65R6vYF+vMCtl9aI3xDiwzo=,tag:EEQSSzBnBs2O1j58GtxG2A==,type:str]
  pgp:
    - created_at: "2026-04-29T13:18:15Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5ARAAlF320yal+JB1OqPJuxbNvy/WiVIFZUHfpeLZclJPyKwr
        jKr/MWtXN9/a3RAS766mad7/SyKOjK5a25BgspycBtL55BKwq3Dqdo/vskeXRO3Z
        DsVBJCeITS7DC0j/bf4CuEvfRP4YVEQGdTJKgpX/0uG0Gc63/xFPTKKU6b++rXad
        H8paa50SIe+qUx2L/K/PKMaPSlH3uBCTqtrB+pkUqSiduhmJkpBNVplXuA9htVPF
        rfYW5lKrltts/u46EhWvBtmWCZTHRSYJiQL0zlXz8Ua5JbAgQ9bBrOvUI7T/QVvY
        SPIAFa3oa94oaPOwLL2TfFzA8bR3YsBjNhYLqRgnY8H8/3dXzPmM5aBqTeluk5gw
        VgerBM1QjiatjkzFd//7MVxy8x7SHuNvgB0RVs1Cr2ALkzy7lqkWhPZo4aAfK7JF
        nCVmGXsZlN40fmIS8VHuexOccNMZklxO2N+znP2vBmPf4uz073i7i19IWhncA/tW
        Ymp8Z43NGMtlQ5u1l/0TZ/Fq+KYcBOp7NITDHT2PUT2vSH9gH09MRZTrgM9Q2VVH
        nQo/Or3phojopIVzZwLLRn9L1kPK53r5T6Y3BxBBh/FbD+IzWr3ylbzJV+Ku6djw
        c8DbOKJenZk3UUloFOP1VZ8nIj9ZaPvg5ixeFUfdXaeKF/tO/PiMgt6tdExLp0XS
        XAELHP1tCekjz44yVO6kdv+27ZzjoN+1y+e3XWnB/PwL2O2J17PK5vD6PZwWLyQn
        gBjHojzvfBkOASpyrpvpy9u8diA4iV2OXhP6UNaAUKYMiYHut8OrAlT1WBvn
        =nunA
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
