apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  template:
    spec:
      containers:
        - name: kafka-exporter
          args:
            - --kafka.server=kafka-0.kafka.production.svc.cluster.local:9092
            - --kafka.server=kafka-1.kafka.production.svc.cluster.local:9092
            - --kafka.server=kafka-2.kafka.production.svc.cluster.local:9092
            - --group.filter=cpjobqueue-job_execute
