apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base/kafka-exporter

patches:
  - path: deployment-production-args.yaml
    target:
      kind: Deployment
      name: kafka-exporter
