apiVersion: v1
kind: Secret
metadata:
  name: prefect-server-auth
data:
  auth-string: ENC[AES256_GCM,data:ciSYQzUaKlgkJkxKSMRoqtOofICeDFLds/10qwNfurQVXeWV,iv:lyHdxWSbBjG6CErZc8IcrcBIo6FP9QVk+/clouBqg+k=,tag:zSmuo6/yGBAIOcylJBLdPA==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T11:19:03Z"
  mac: ENC[AES256_GCM,data:btY4Ud/RAzScmhxiUcY35odVXtG8xA+VzM1aJ/2Mx//p7ApZS/KXL66JKtWKOFd8tMu4SLekzTq5/Bcf4yZ6KYRUxS//2g9rde7CGBj49ByDcmxXNCVGW81X9ZoDBbFWYOookJaFxQWaR2uqA7X8+ZxfoCSSS1gL2WgniGUreR4=,iv:wIih5VCuMlBwQulnR06sPAleIQClT/P9F40CGMUptKg=,tag:CiDFa2pMh53FtdsEwpI9yg==,type:str]
  pgp:
    - created_at: "2026-08-06T11:19:03Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ/+KFcR9wUf3rAPdp6Yu2PCX5rCwNIaA2/ajTewIMtseYkV
        XjRemAKFfki6qREx4nAjo8cYYb3nus9GxzsqmnlnokGf/Yv79XMdjijh1xjJcd+B
        rXTVQ5c0xH8xuGxrc236983RRKpWCcX9wu1d6J7Embit1SRtO6RKjpnHrgsCi3qN
        8xtmhjELsmAJ33P+w8SBSQc7PGWuOzfR8RjfrQgGuSDnwyWMc4iZZKTgtYE2jeSp
        GikSjrA5SxYRa1L21+4bttaPQDs4xXIcy8lo3hCTSW+c1eQ0J3R7O2zlavEQWpjm
        A5T0zjjWfVXJPwCF24fnUNsU4CWTSq44BP3hSOH5JJOtE9ap0GcVpaoxSTp0pwVf
        MqA6FNcpHXFVUFo9wmesEDsXa676XtHlulmoGNTPTpFJN4COtVQ7s+GWdpWMeWsB
        JdLVMMVnA477ai93ddeKL4fyYmxmoF7tmfYYLhOIL1kF+xwhulvwGIX51Ob4x55L
        muLHLaqKY8ZXCciATtINgFrBIggK5FNzUrqiOKkinACAUBbSex/MlqsceCVMFEuE
        TRpBGrBW53HGzDUJ16lDKwiwoHGIr2BgUIidfYbdYiAQiPvdhXpVUgMVnieOEsFd
        mzL42s/SnhSAlMMm4c1cejRaB6qO8aA1m6Bqvaldqq7SuHiVBo+SPI8/9bd+XFTS
        XAFgDyBp6kx1XfwU6fvG9vbcudQG7r56ZFXXlcC1wYeqAwVhM9KdOrsdJ4nRpIyV
        zWPby5CxMAU2XL1bcmWQNrZDOLT2DIQxTDGJ0OFQjzwVWVtGoTJ3ltuUgclp
        =ptDC
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  version: 3.13.3
