apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prefect-worker
spec:
  chart:
    spec:
      version: "2026.7.31163938"
  values:
    worker:
      priorityClassName: staging-low
      apiConfig: selfHostedServer
      config:
        workPool: staging-k8s-pool
        type: kubernetes
        baseJobTemplate:
          configuration: |
            {
              "job_configuration": {
                "command": "{{ command }}",
                "env": "{{ env }}",
                "labels": "{{ labels }}",
                "name": "{{ name }}",
                "annotations": "{{ annotations }}",
                "namespace": "{{ namespace }}",
                "cluster_config": "{{ cluster_config }}",
                "job_watch_timeout_seconds": "{{ job_watch_timeout_seconds }}",
                "pod_watch_timeout_seconds": "{{ pod_watch_timeout_seconds }}",
                "stream_output": "{{ stream_output }}",
                "job_manifest": {
                  "apiVersion": "batch/v1",
                  "kind": "Job",
                  "metadata": {
                    "annotations": "{{ annotations }}",
                    "labels": "{{ labels }}",
                    "namespace": "{{ namespace }}",
                    "generateName": "prefect-run-"
                  },
                  "spec": {
                    "backoffLimit": "{{ backoff_limit }}",
                    "ttlSecondsAfterFinished": "{{ finished_job_ttl }}",
                    "template": {
                      "spec": {
                        "parallelism": 1,
                        "completions": 1,
                        "restartPolicy": "Never",
                        "serviceAccountName": "{{ service_account_name }}",
                        "priorityClassName": "staging-low",
                        "containers": [
                          {
                            "name": "prefect-job",
                            "image": "{{ image }}",
                            "imagePullPolicy": "{{ image_pull_policy }}",
                            "args": "{{ command }}",
                            "env": "{{ env }}",
                            "envFrom": [
                              {
                                "secretRef": {
                                  "name": "staging-importer-accounts"
                                }
                              },
                              {
                                "secretRef": {
                                  "name": "staging-importer-secrets"
                                }
                              },
                              {
                                "configMapRef": {
                                  "name": "staging-importer-config"
                                }
                              }
                            ],
                            "resources": {
                              "requests": {
                                "cpu": "{{ cpu_request }}",
                                "memory": "{{ memory_request }}"
                              },
                              "limits": {
                                "cpu": "{{ cpu_limit }}",
                                "memory": "{{ memory_limit }}"
                              }
                            }
                          }
                        ]
                      }
                    }
                  }
                }
              },
              "variables": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "title": "Name"
                  },
                  "command": {
                    "type": "string",
                    "title": "Command"
                  },
                  "labels": {
                    "type": "object",
                    "title": "Labels",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "annotations": {
                    "type": "object",
                    "title": "Annotations",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "env": {
                    "type": "object",
                    "title": "Environment Variables",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "namespace": {
                    "type": "string",
                    "title": "Namespace",
                    "default": "staging"
                  },
                  "image": {
                    "type": "string",
                    "title": "Image",
                    "default": "ghcr.io/mardi4nfdi/docker-importer:main"
                  },
                  "image_pull_policy": {
                    "type": "string",
                    "title": "Image Pull Policy",
                    "enum": [
                      "IfNotPresent",
                      "Always",
                      "Never"
                    ],
                    "default": "Always"
                  },
                  "service_account_name": {
                    "type": "string",
                    "title": "Service Account Name",
                    "default": "default"
                  },
                  "finished_job_ttl": {
                    "type": "integer",
                    "title": "Finished Job TTL",
                    "default": 600
                  },
                  "backoff_limit": {
                    "type": "integer",
                    "title": "Backoff Limit",
                    "minimum": 0,
                    "default": 0
                  },
                  "job_watch_timeout_seconds": {
                    "type": "integer",
                    "title": "Job Watch Timeout Seconds"
                  },
                  "pod_watch_timeout_seconds": {
                    "type": "integer",
                    "title": "Pod Watch Timeout Seconds",
                    "default": 60
                  },
                  "stream_output": {
                    "type": "boolean",
                    "title": "Stream Output",
                    "default": true
                  },
                  "cluster_config": {
                    "type": "object",
                    "title": "Cluster Config"
                  },
                  "cpu_request": {
                    "type": "string",
                    "title": "CPU Request",
                    "default": "250m"
                  },
                  "cpu_limit": {
                    "type": "string",
                    "title": "CPU Limit",
                    "default": "1"
                  },
                  "memory_request": {
                    "type": "string",
                    "title": "Memory Request",
                    "default": "256Mi"
                  },
                  "memory_limit": {
                    "type": "string",
                    "title": "Memory Limit",
                    "default": "1Gi"
                  }
                }
              }
            }
      selfHostedServerApiConfig:
        apiUrl: http://prefect-server.prefect.svc.cluster.local:4200/api
        basicAuth:
          enabled: true
          existingSecret: staging-prefect-server-auth
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
      livenessProbe:
        enabled: true
