apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: staging-latexml
  namespace: staging
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: StatefulSet
            patch: |
              - op: add
                path: /spec/template/spec/priorityClassName
                value: staging-low
  chart:
    spec:
      version: "0.1.5"
  values:
    ingress:
      enabled: false

