apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.anubis.servicePort }}
      targetPort: {{ .Values.anubis.containerPort }}
    - name: metrics
      port: 9090
      targetPort: 9090