apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opensearch
spec:
  chart:
    spec:
      version: "0.1.1"
  values:
    replicas: 1
    storage:
      size: 200Gi
      existingClaim: opensearch-data-ssd
    resources:
      requests:
        memory: "24Gi"
        cpu: "6"
      limits:
        memory: "40Gi"
        cpu: "8"
    javaOpts: "-Xms10g -Xmx10g"
    