apiVersion: v1
kind: Secret
metadata:
  name: importer-secrets
type: Opaque
data:
  IMPORTER_MW_AGENT: ENC[AES256_GCM,data:iboOQxEPAbVkYCNHipSNXcD2yVO7oHmlvZALFskcS4x+FTG39GmdaPb6p5ChN1EbxwyTitBUjlVMa2mQwgQXKVvZ10etLZtTRNY9fZ31Dj+WING4,iv:wXnTEhIfv82Vd2v4grHOv9Y95SsFgLM+19JwLLbmNZk=,tag:XCpUsCofOUcKQIqiWdwn2A==,type:str]
  IMPORTER_DB_PASS: ENC[AES256_GCM,data:iGMxhmKyT3RWzCmoClS3f+7jHa29nTNaak563JiFZqZ9WphJ,iv:mSd/JIIWLw+ZS8PmiFfFtKOEcZx+ulSG0Ifl9zGeCDk=,tag:m0p+AfD9L3EFARbvpVKi6A==,type:str]
  PREFECT_API_AUTH_STRING: ENC[AES256_GCM,data:Jfz2FlXgFUaDyL7fVzKt/NiL1VYC73qbqkNgi0jVbK8xQBLs,iv:gNZQnLoUS+a1GZgutgj15DHW0ya4gTm7qcF8l657EtE=,tag:t3YAqtoZSlZ25+N+8s4/PA==,type:str]
sops:
  lastmodified: "2026-03-12T10:44:01Z"
  mac: ENC[AES256_GCM,data:rf8xOwwtJDIycyQ36xKA/dhVnaRRypmz8FUB2H7hyacaeOOhR+ccn0NcbRwonleVQOK1OpKompzyukzMuQYtJLfL4tWU2GLcuCzt1fsfzhX4s2jKP9vWGv8hNZFfbhKXhKAhXElRe2hhSRKOUQPYMb4QzL7b/rXjRdIakfsuF3A=,iv:6wagUC+Gvb00DEgGQBE4KVhRbte9+juaFYgrRaCySbw=,tag:dQOtmXulCQYxTbE2vVe6MA==,type:str]
  pgp:
    - created_at: "2026-03-12T10:44:01Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ//QH0C6Yzk420KgmWN+jyQFRtWimxbIqmG2hLABtrqTnmr
        huFUQVdGjvtIS9s2qseTQ7/o4fzwlV76V5cTJIxY9CgvBenLbX7D47axyBDvhGtP
        0MBhozxZCrR3vOgDnzZzWrZ+5A9kYUYqWSeLMcsZcYjXKic+HaXVq8eLqVa6Yb+U
        fQ2xYcXmBSkAny1vC/XOfPI3LHcdTY+OxjrTHcexyDDensbX4iRMOmpMjUI0Kr7L
        LXYzNkhCiDqMljK4CEzppnRKyzea12rH1EvZci5HUKOq37DJaajBlKp+Zq2IRxrQ
        3jMiXUo5+3AmJL0ZNz2MKAPHSks/8bjDgImLd6NolE0UP2lhGJWcd6bw4TiJ+Dzp
        tD/lu1OHVrww3vV+iGkzTpbCwjWJ/hMu19Eo1gzeSon1a3X1v6tV/KdsBrm5KhoO
        1UsbIBbHPIUlRac9PsjFCxrzKTtzVnabyAU/UogGnxE6mvfGyfCL7LjeW45hDFel
        ZcG70O4mL2zTtxo81NoaK7ob4Y87JqC6Fl5prLcreYspAn6nXQWc+xRb7StftT3D
        ALnCnsDafv1JAiW0VKdow3WeOTUTi/j/FmZLjSZZPCJHJEMos9WeaHwEfuJmLBmf
        jPGKfyVT99Ei2gRlLJcUI+Hl+2LTtCoh+RkDa4LEKeMEvMbIEJyIvXVTk/j3WKnS
        XgFslrhsu3Gz+VMoGFg5TUjUoBBfhXMNTciWkZ0XPQyTbBslPI3paqJ90TissJjn
        L47uWuwNfZS6RQdam3JOhn6nq0R6BNR9w7Yte1NpXlBxHFqWiajLz6AZvq+vA7w=
        =0KHO
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
