apiVersion: v1
kind: Secret
metadata:
  name: importer-secrets
type: Opaque
data:
  IMPORTER_MW_AGENT: ENC[AES256_GCM,data:cfLLsWpNLW3RrRiJUMYairepbtof1C3I8fPVOkM/d2F1RcIARfnpAG7xkEbTsOf/PihYjV1snM0Ie4/rwS2lpOhLkyGQIZgU2Bp2c8IUzJXa11oG,iv:B0xtb7fV88GsqWFRwJCsSz2ZDqoaLpSMiIbviEwOYBE=,tag:LabJlwFcFiVgKTalcj0/1Q==,type:str]
  IMPORTER_DB_PASSWORD: ENC[AES256_GCM,data:9g83oRsO7asrS0zuDGm3KcNzdc8kO4W/GH54EgRxIzK0yCKV,iv:I4z29vScGpka0J232uy8LS7VIAZcud+dLFv+XlnWefY=,tag:IGsLQW61beIf24BbHgsX6w==,type:str]
  PREFECT_API_AUTH_STRING: ENC[AES256_GCM,data:deEqRyl4IoAriBNSJLlUmiuTtY60uYghNOrS4PbSohJHkWTX,iv:EyUDrO1g24w3fpef4om5timgxO39zh8RCqe2P5vZk1U=,tag:TNMR8fB5eFuBRKe1jPNmWQ==,type:str]
sops:
  lastmodified: "2026-04-30T10:01:04Z"
  mac: ENC[AES256_GCM,data:5Cwq69t1wXNKYAMOy74bZ+0F7m8CucVbSEmibROrmf2Mdjnd5hP+1uJGnTSuvOEpy3FRoiTVofWALSPBT5rbBR1KqkMqCLPnHmTjp2E6E1rJ+hFIwrk9rbGZQlDNDoGSFuCq1E7gG2ujdKjC7GLPUJVt8IG86aDaUe4aG9vfUsw=,iv:Oe190kJ96NiN6/AOUMLK1OrBKrQCCwHCIH/shQOlxb0=,tag:qDldTb3DwUVnM9c+QrQo9w==,type:str]
  pgp:
    - created_at: "2026-04-30T10:01:04Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ/+JvMO1rfiF7vFbod7IXSvApNR5jaymeIs6c9D67nTznqJ
        QrrC5D/bqwGRdtw7EvYhOi2FgbSw/XV5x602mic4S0OXmuST4BFnx8KWhnzpssjC
        2r2R16en0D6WSL8eV4V+LdJOuHLspBCZkCHCGcYQ5T1f/N0JaF6Libt/t+Y3jApA
        N6YE3vMeK/Hd5LxJc0xYoY4X5gvMH2tbOugo/rxNdmAe57OB2TC+ggHC5achzWfc
        Lb4YIe/R3/rJGhGOSF0+AEltK+75G15Ddkr3K/xzY7bVM7zz+qyvejepQtgNae0M
        rv3FojY5fjAUjh/YfaW4KwJCV8ND4z7i/udnDv8HhOg5DBtesuWQ7KOEnFofZ9o0
        9/LloO79mKATd3uV+TXuwZm5x+j1P+kTYmqZ8QI1o6Ulu1Z5PP7WIvU1qp0UeuiU
        kzDOcQf7fmGHpA8KnLtaNbGkGdGvTj+Qw29FZASrJrcccZeO6I8DHb+9VDMvg7rN
        zg1Pv0iz749+B4fWL0Vo8aasWhDz1/Oljogt3LWj3L55sZGRrz1JE9dNI3/Vz7kT
        4Ru9PEP46xsO0+B5OlYjtnoMDWH3wHWEkSb38bJfoWo3NDL6+k1Vl9hKYRB+Dtf0
        mteQyCcAmYcCXr8PvpsAKN4itG5C34he1QsBTAz1cu7GK6u+wXKpuk2tRRXQA/LS
        XgFo76V8DlQBnKaPvsrMiQwLuVJAmgFyblyO3AJ6lzWMXFlmgiSlFQ5FkQ400PnJ
        19p95Kd0L0L1/He2i8aO5oSKRBQx84e209RmCL+YOM8ji0TPucK6Qz8tJYDYDM8=
        =sP9D
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
