apiVersion: v1
kind: Secret
metadata:
  name: go-away-key
type: Opaque
data:
  GOAWAY_JWT_PRIVATE_KEY_SEED: ENC[AES256_GCM,data:uLRxKsFGe+2ezRWMvTier2T+v9qjyu80w9A7FZvvIpFZ1MkDLyhnwxHiCJfJy/T82Um0klHCyaiKNwt+zf8AR4sXixathda6RU5u1iEZl+naG8MpxCM8Zg==,iv:HMfErnmRf8gqGFide/jlYRpRB7E271p4X0gwhngiWP8=,tag:nNSJm1rAvmw43nxPaqmLtg==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T12:13:31Z"
  mac: ENC[AES256_GCM,data:NHik4DPdFX2HqPLdn+U2I0vsxk3rfKB8nxwihiTiBkysw1ZiNzw9xjdj5ezd5J+tOf64XojiPiZCXl7WPVF4NhT0hXv3cyu6eJ9XLVR5CouH1C+qxLKjO0kGIrbY8L/l/XBG8KdXzZWsq5u6VBBNjtaZvl6wYUZaFJ0bsrCq2KY=,iv:1BKbgBQf2qDuSPtjxqcvZlqKLda/kv5tMYfseBcNVks=,tag:D5g/MUF5a3frEgxmnsCjhA==,type:str]
  pgp:
    - created_at: "2026-08-10T12:13:31Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ/9HIRxQQJXfR5bIvZLC9ALGlbXW67Ah+SCi6FF6N4tbCE0
        K/s+0hyZRq0AxmDP1jFQbrBFUgjxebBOrcZx6Q4GwLqV56DQUjJvVIrObkqo9+HZ
        J89xJqhgY5IVyWDp52+OQgADU3vgu75kv1bPsPASxiiJB/RKuBIHCZuJC1S9GTGq
        bgkey9K7eF1kw7vkSyP9ZPc6CdreIKqlom2sCi+0fI3jnSX3NKHOygvLmfL43Ad8
        ledMVftNvInl/+wYSBFXM+7FIz5H2jHm0KK1nqcD8qk/IjAAWL7WrHunc8zZlBk2
        1HWQj4NViqCuYK0Xkgj/RkUQ/H3rNiSiv3TyP1tEmIIS8yePQzbHm1YXUiHPYxhS
        bAUhbXZVMUBU/KhMrABJEg1Mu+zYJwS+BjJFJFMHO+47DQwGiUobO7HIB+0XxkhY
        OhjPZQ4GiykEdhN9WUhGoBfi7WgZvUgeid4kOFHbYduG01S3OqDwDJfkrtenr3Tz
        zp3KxVVuwi/n7SURgwguivUl4S2dAm/vkt07KrB9kId51nEcMmQK5Yb/eK1J7r+y
        M8Egrtq4Oavxd6rl4r0VwZMpoALjmAGpTIwcs2f6G1/5O58M99aiOUX7TKJPkrql
        kyZhcXp3k+V48RsUidMN3uXbKalNPCC2btjw421xf1ztDKeH6LnewV+jwgkCGiHS
        XgE/2x1ybeiiqdfLFxr8EoOja5wmenLv6m0Q/u1sukG0Ny4//ypPOHJuVH0BlzjU
        FHWLCaLE7gJrU3n3nOzyA07wBFlLN++Tj8hsrLcn6fuG5SKkvF5gEbAhmZXC058=
        =LiPo
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  version: 3.13.3
