apiVersion: v1
kind: Secret
metadata:
  name: go-away-key
type: Opaque
data:
  GOAWAY_JWT_PRIVATE_KEY_SEED: ENC[AES256_GCM,data:KkunzzJCkTdKwrLBFAaxO0jGW1lB1g101f20G060TiUIToS6m3+T4S3S+QJ360aRST55IIcCYyPgNMQFelrbtwpZxEpfrRsGvX9yYmUbuQbUTBmGhq9EjA==,iv:qkCwadUO1Tvomk4GJyj6IIDxvk6+lmi+DWiJTyDii5k=,tag:mLA77L65f7Sy7i+n7/Y8fQ==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T12:36:49Z"
  mac: ENC[AES256_GCM,data:5ZLkmch1W4P3Uydz9zyNuYrGQXpFUVuNf7aGEP/9cC0oZDxblPt9k4nGvdgXzEToSyjO8e/z4+ArdJUK0l6ejrEIGjzP7XIHlFY+rt4nNzTDEijc7yBApkWHy0ImTYnLWshQcYHzhBCM0NJh8hT2gEmTOb7ml2uS/5ro4hMWfsQ=,iv:6QRCOW7LEJz9kpMQABMmeUi7QB0eXWn/P1M0TF7l8j4=,tag:Ol1L+JQNAv5iFRmDOMCIDg==,type:str]
  pgp:
    - created_at: "2026-08-10T12:36:49Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ/+IvbhrNsHD/GTZTycULISNrw3EDBbuKqfCteQdRY4YqBn
        5rx860AcFXtSYuashH3gNLQSdVUzqKnQnM416b/BCskHzpgUxvVwlc/jVNoAT9K3
        uQzzOYbZtVYlDA7s3u2eN77nComO4l4s8YFwgJPg69jTScHmhqhU/oS4MPQuIZ6m
        qDnn9plQ2Lr+FN9fvmv3aiINLj35e46wLKt5RmMvEpvrZLoeNY7fjLFunxd/EhmU
        Zy1piv0nkTsE/DeNVNfqogGCAKMQ5gL01unuggiOSGSWG+rWpxl2wWOu6kEFZthh
        tvJt6kD/DciGjtKnrW0e/XgdkjizQjYPiprl2pNwQlLw3bVFHReR7+cr144KI1jf
        gs5eDK3vvccV5nkGEDfhllJRhtOQeczzyo95RhI2mmVlsi1yCSfT+hHb6gj8z0G7
        CzwaYCTlRgcjZetl5e8JZ52tJ1A2KweO8nbUiolylCMkCHtE4Ona5kEE07TVFpT/
        m0OhP9zu0y+VU8w9szZCiMD8/l6ooWpVlg3A79yTpct8QVJ6o9ZN8ol4dnAjs7fu
        CrZ5jdBDC5V9VdeouzbKUzcWV8KWBNfBWRbpgbLEV09CzXdcuWnY/TiCcJIyI7CY
        k/Ul/DBfBQodvuldQfWBGFkKWkdEQciPOpt+6QwVcy51OShJyQVaT5RpyzDbKjHS
        XgEYGaEZsgmzvP0HubxPY2dKBlLFE9f3AKBKUAXb5Kp7S0YnHd7F0/B2kS7KJJcM
        KLZZdy9A55I+eYSr8s/fta+AP7Y4FX9Kl7uxRqY0DGq/ejdye8XEMZeeFQxR7Yk=
        =MOfo
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  version: 3.13.3
