apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: go-away
  namespace: staging
spec:
  chart:
    spec:
      version: "0.1.0"
  values:
    goaway:
      target: "staging-varnish"
