apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ipfs.{{ .Values.global.baseDomain }}
    {{- if .Values.admin.enabled }}
    - {{ default (printf "ipfs-admin.%s" .Values.global.baseDomain) .Values.admin.hostname }}
    {{- end }}
