apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init
data:
  10-configure.sh: |-
    #!/bin/sh
    set -eu
    ipfs config profile apply unixfs-v1-2025
    ipfs config Addresses.API /ip4/127.0.0.1/tcp/5001
    ipfs config --json Gateway.NoFetch true
    ipfs config --json Addresses.AppendAnnounce '["/dns4/ipfs.{{ .Values.global.baseDomain }}/tcp/4001","/dns4/ipfs.{{ .Values.global.baseDomain }}/udp/4001/quic-v1"]'
    {{- if .Values.admin.enabled }}
    ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["https://{{ default (printf "ipfs-admin.%s" .Values.global.baseDomain) .Values.admin.hostname }}","http://127.0.0.1:5001","http://localhost:5001"]'
    ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials '["true"]'
    {{- end }}
