apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: gateway
      port: 8080
    - name: swarm-tcp
      port: 4001
    - name: swarm-udp
      port: 4001
      protocol: UDP
