apiVersion: v1
kind: Secret
metadata:
  name: ipfs-oauth2-email-ff1bbde59436c6bd
type: Opaque
stringData:
  email: ENC[AES256_GCM,data:yNsnxE6hkS+25oY9YZiUFRFMxtVJy0R6ag==,iv:9UE6cx0JPUs3zt9DNArIUmtiHwGMXl7m+UqnOenPhXk=,tag:82p4QVFzRCgqW40kUq6lww==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T11:37:46Z"
  mac: ENC[AES256_GCM,data:daSQUPniT166dHSih8I1vidGo0AudAzDbnSI2+LdqxQE/IoKUyz1uTv995R1q827Fu/usMVj7whMV6wooxxDbVJIx/u3M9LvCA5QADpKhNwI0d7FrQrGzacjVdZeOMfIwTgQV/IaXCjXCl6MDEuMQUwtUDSo8MU7PftDDHe3nUQ=,iv:N12kpkgNkIdnE80GEP1tOofjC+O9AzeRMR14i9c/HxU=,tag:grwOZNqQwBDk95pnCKIwtQ==,type:str]
  pgp:
    - created_at: "2026-09-01T11:37:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ/+NKiBLH5veTTV8L69pVK7yVHw259UvCmidhGsT8vm559N
        Oy0Ycn4piwRa2huCIwHiLaoo4KUmS3dRY/40crAjpalc9ups+EsDTvd9tqaVTeux
        cirugbVhRmZsG0UKw7buWOPPXbHsFI9nYHkQjccpG/NB1JszBbvyl3MJU55rvUZq
        yPrkUIfNSb6UJ+/FHPVKM91Q9Ceoo/jPJVbjeiRJVVr1diY6DncVIKsQRWO7wus4
        F5afh8JNXCTDJOTI/Cimmg/65Wge5GUCpEiB3EvYi1hVPe+2Fb/+1FImg1P+JA2h
        g0uRyYokq685iUMyVXibUfCY0LqV5zROIFNiLkzdG9yM3Ev9g1Uf0gG/ZaUSMQQH
        +cw+xjVE2RNAbbC26t3fWSWurRfXW7URcI0GsIHTU0iL7PxXGF6wdvVph6JuNxMC
        JDcjLOhAkLwSZANVrb6IP7PrwsRjTP1cRY013D5Zc993emK+q1esrCqg4PG3RKx+
        79aJHpyQ4SXBP5QD/d6z2+sFk24VxZ8OEGJgXA3kx50QyrIXYN+whezV8DBhTVjM
        5r72JZEYtYcc1zG86WQBDCBUUr2YX7ozCQs4mEFvoP/2mDdyYhK+XLCztfRQkmyy
        qDiWxAqe7gwIFmEiT/EY0UTEi846NqEqZNxFr3dmILEkBFHahYYSgxkguf79nPXU
        aAEJAhAVziBM0MEM/avjAc/lSG33IjEM1EtK5v1+g5TaJPS+SZRARdRvfdrk7p/r
        +9eQy1avQMSqHri9polHJ1OV8y/Rmf3Mo4Zo19fTnT55d4GrNk/dnOavSY1O6Jr2
        9s4vL4D8M0dM
        =37iy
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  version: 3.13.3
