apiVersion: v1
kind: Secret
metadata:
  name: anubis-key
type: Opaque
data:
  ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:WrTgpbHifN+7nJ8RHVpm8xJwZTKPboVEaKAYz/1jtv4r2btZkmL8b8f6m/ItX19VwQ1Q2KES/y7HGzFRlWjPcnFHyjhakvfWZCLyi7SRw8wyYjpXewrmlQ==,iv:gLGrAAOQRUWCnZeqB0myoGCtZptHGjmQdYbCUMQQM8g=,tag:QtJSc4UxXOm7gNy8Y+RV6g==,type:str]
sops:
  lastmodified: "2026-04-29T14:16:02Z"
  mac: ENC[AES256_GCM,data:MsnMfY3/bqIctvLEXHYreIOOrIZUzit+G3RmrtocphbGFVXFr1ablFJpVGHaltKB+mjCzJ1mhE2NFZn79D8LRgorMMV0SjdS+jhDh/4dbX762tkct2sjcQaBItIOU3P8jrOb4ruPmvWfPCH0gCZpFHHTiDatcC6wU3Pb349Tsbo=,iv:SHuVDE4BeC7rsPJij0i2q6IF+8HU0nlpGtpeHFm7xY8=,tag:Myg8VdkRyj/TxOKxcQbVcw==,type:str]
  pgp:
    - created_at: "2026-04-29T14:16:02Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ/+LIsNyNqvziGt7Daj12CRwLZuJP1cY99/4h8NPTf8ROSV
        f0G279KaIYrF7ObQ6RxU8aPVv0wfrnlEQxpxjg6lbcaSTGeJRTFfniEzOZNTKgSG
        pfMKzybMJg6KB4oCYZzXHtuSrdYUqREaKg84ZGlOROxQHLLcKQUoajCSZdra5G8I
        ZnG+uTGFId02QK9OsARDmKf4g2kLjgfLkKjTmtkTQGJHTkKpVcTn2uyfgqyOCs1f
        89Gbl+qcDx97z6VhUwA4t0X55XRwoA8fUzyJnPWrVLYd8rcBoP1+LSZbNlXSuxqD
        7ZfhkpCPlH6SM11skJ++QvCxOe8ZYNJ6nFWUUD/IOLvNvQ2QVsu7ca1bCzfVOpD8
        W4J4YavL3Rq68Pel+OMgsz3gK7aTI7VXVvjZvcFhI9kFS+pRmG/yP8UpqhojBKDH
        ssQWhZc1/VzcIsS1bFoMOpsnsTRkuYqXi3YUEVnCl7EREuxbo0OWp7CYJ+6fwR5W
        AXvSWnIVBF9W5hNsU7fAI9f9un70XHT4TcFb4I4iBSuBxyeRjRlEtiUBBqCMFz6V
        wpuC6cgyC0VWwH0xy1E7IvoZpSQHShDfAQ9n0xVZbtPD1umY8ZSx3pstzJ6urPw7
        EzY+jCb8nqN0jcx2YW7UwUSQMM4PoIAh8i4ppuE6KOUEzCiT6NzyVo/bOme93DTS
        XAEbMEVXfLmxKAAWyZt8KKDanwpcrX1YqRglJrDEdZ/ZXs7+PlP3X6o0Jb+3NxCQ
        YmyaeX+Ti812UQbDbgBkTMuF2UzZKU7yd29hC/8Ii3VJ+7gADph4bfPo32T2
        =aGg2
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
