apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
data:
  CLUSTER_ID: ENC[AES256_GCM,data:kup+9aDiqYD6LF62YnhcuxaSZF+Hk4U2v9+RXqNbEhc=,iv:VAy/F5aHbNtfAdauksqe3T53J5VJhqWCcXGB9XoVplY=,tag:zH/WZ2xWfpw0CMn0ub0mcw==,type:str]
sops:
  lastmodified: "2026-03-23T07:13:47Z"
  mac: ENC[AES256_GCM,data:j2IovfvyIlecECr6HmZrMZSk50E8O0YVHUwHf20dtoeCCX4iKSP8ap+vOQ2pHzfqc25ydGXpuMClmNr7+MYksSiBUZdPXT8QN8H+Kdc6TkpB9B29qaf13flvHpUxYaoXRMSUz8iPximScYiABtxVFyTZ/9zDpPByDZ3VOrjmqfA=,iv:anGrV1i3sYxQjJnBQ6tmJ5vvHC2O4l8DvJRrwyMpmuo=,tag:NAoy9JfVaX1laf90fAcpMA==,type:str]
  pgp:
    - created_at: "2026-03-23T07:13:47Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ//SDV1+PFn9aQDZ2HOeiL49P+eUVk+3KqZkb+SQpo8fVcM
        PWimqObgzAybxsyisyx/+OjvGss68lOHhIwiJIBcsX+BWTRX8h8zhFObnvhzj2yw
        3asaWxygyfSCBL8ovXxfKtVzsNKa6JLHKhY9/tzD/27EyD6JTUTyS0SPJa2ela7o
        PZAUIjhCZKXsluZoZFFX5ZG7k78/rRY7oFGnxjIxcsa+zsnRJHwK86Q3iCyC1ugW
        6+CltNY89WSALdglWNYfRwelXpVEETowkhqd1IMF83j+q91pi6AzTvYdpdbk2Okh
        VbciUedVDi6AFjdoW6QF2WjyCRPqXIzOJSC49yUW8k1x1KADVowS6bEe+XeNf2rJ
        K2E2/uA4w4aHvSXsaSfDR5nco5aWtvgpoC00sOvcTRAq+6cRQw4m/hmewKHmHXsM
        3EMYqaBAlaw/NQnhIwmC1aqq+jAPLwuf6TraDS79PLkPLdsRtpFxu336JKPJ3aMG
        Xf8krkDzM3OvZBXfdKK4f6HkYEMPD7kIZ+7PKhzVBT+23fAGBM/BSRQkUC7BfHqn
        gT4jxDp5OL0dbyASTBK6MBUfqKVNRHE29PMXwi4RhFaVKE2Myj1ZAHMBg69WVxzR
        Sq3yuqJa+1H04y4JZopDIp/Vhx7ZylCGucoAJKSjH7+VAzsHzbKV7c9x9R+hWlfS
        XgEiR4uZFOo3iwGQeyPOHGRaiesDQkOowpZAn2gK4EII3PIiZuWHcQDI2jy9T1dn
        o4XrFA+cNlVrQHtvGu3jEc+UpWtvXaL1YbH9/hXqJZfdsyNOKqimAkAPeY+d2ME=
        =fDCa
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
