apiVersion: v1
kind: Secret
metadata:
  name: prefect-server-auth
data:
  auth-string: ENC[AES256_GCM,data:ICxdDK1e3/Gprm8DFuc8VncctvNHPQsAYhfuT0PmPYMk5B7w,iv:rYW+TgHnDHmWXxWPtRryLb5WxLBYyBZEcByF16QG/Ck=,tag:BcAohf4dYq1AZiXQ12Pt5w==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-14T05:49:42Z"
  mac: ENC[AES256_GCM,data:2Ti2FrbBitJbB/tsuv1+h/MJgw5XOsumToQ9dxN5X4qK6joThC57aSCRa0B+6dJq5ZmwJlN2zE8GMxGQ91LylDtUjVYxy0KwsqO75iRgq2+tpIAIIuCKVGisNw+zEAWetGDhxk19cnBTFo6b2+v8a17uUYQCzTKVeLQ6Q5CZKxU=,iv:jZ1eQ1mJV8p09Yt1xGfbcMAdPhz36d1/HYCVVXcdqWw=,tag:XE3ZZpcF5XRK1a6Zhvs6Hw==,type:str]
  pgp:
    - created_at: "2026-08-14T05:49:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ//Yf8nNIBvmWCCFuvisuuIkS8Nc4b6MfXK03XPssx17JFa
        NorwpROldOzDppYb6AtWkgJ5l91Hg+pAKjqxhV5sSGL4NWxc/DsxGU1HNCrltGiz
        7kFETr9nRT0o2sgTDeJ1PWdtpV9bL2nvM+uQ4Y+PZVk/FBf9RmThom/OI1iFtlnx
        Cj4UepEZsnaiAvkACvVkjbgn93s5s7dvyborPdfEVAwRhQ2aS1sA+ZUGaAOUKn5g
        g9znWuZo2zaHhsksFvjAtB33bsZLPR7huq0l2FNtt/s/JptEBQWAKBiqeBShmbj2
        LP7a02otH7g3rkCjfLmlcey8YjifEN25M9j/kdTlzw4+P5XpvK6h+Y85OzDyV9I4
        4A3iwvGJ3lqXMlgfs3mQqVQN/C72Sn5FjscOwBCX20MrTAFEsivdMCEVatIP6YIE
        tG3JDUSuKBaLQZ1yb2ZEu/uYam+gCT4GDi7vd/89t9oECj36uJXQqV9XYbWG4X/V
        2/RsyOUyCY64Tsp3avKJ+Z6W54yuFeLEqPoi1gAj/L7qxEtVLVHHBkb0n1uEh3GN
        xhi4PnrTQObTDd4lcTKjIzre+sUa4J2I9nNeCJhgqWDZgyVa84toCmz/BiQxzzQ/
        yK3hKtBCpCWbJl7jTjFd5wCbDoNe45jwSLvEd3BSpWqe3IvN30Y7DpRI6YdDNn3S
        XgHqSpxh4I8Z8kKSieoILt4oIsFNQm4Mv9c8SsQJz5XxNJVhW2oq/jsZTHcgzl4o
        LWltyPOg2OCclk/sqPD7Ui5bs7Gq0XDNoMr7ShlO/OqWCf9Cva93YxXzAOEWpkw=
        =8MEi
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  version: 3.13.3
