apiVersion: v1
kind: Secret
metadata:
  name: qlever-secrets
type: Opaque
data:
  QLEVER_UI_USER: ENC[AES256_GCM,data:KOwXY59fUak=,iv:6oTnfTxDVkjfQcO14rzasDB2Ieyh+rWnzn8JslELUdY=,tag:GzM8zgMhnqFHRTun0ZFNAA==,type:str]
  QLEVER_UI_PASSWORD: ENC[AES256_GCM,data:Drm6vndyCLae6oTnQ16ijLgZ+fAYzDldPcuUyA==,iv:yt8OW36KYonmtonZW+b08lmTO9iKPCIBit9gTweS4Kk=,tag:hETCDg12rgeNM7qN75KbCQ==,type:str]
  TOKEN: ENC[AES256_GCM,data:Mp7nqsiNvfk34VBbPxJJnDpVXtUzaGGjXU0qjrqSv5h5Vu/S4tz29TXhN0ObKdrgEZo2EWn63Ezg0AwrunkZ7MONJX4HBCJG85ZpeWRRftDRVO3AMC8UhQ==,iv:tqXzEGFGK21dKyQ2mWVvEqMvM6qArD9c6QKVI3qh2nI=,tag:VkP7NUwXr/dZvwqFgKG8pw==,type:str]
sops:
  lastmodified: "2026-04-24T09:11:37Z"
  mac: ENC[AES256_GCM,data:EymThhx03gtdiDuJkxRWs7wEmbuVM1FlRHMG3erWBf2P9QGsqXFDYY3EfbovI9ojq1FnL0LMP/oARHO5n5JA+D3oBVEfWijOOayb/aUCFFDYN6+kJXtUOZumCAzzeUq+gpPmXdAEIQ2cYjj/PhyWt2Lbtj3I88EeyVmWkpb+fao=,iv:pfs4YKgW5J2V0xUVRgbw07Hk7THhVyKVIPA6nAkm8SM=,tag:pidqCsTVxpn7qyeDghb5/w==,type:str]
  pgp:
    - created_at: "2026-04-24T09:11:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ//X8SY+cOHLAQPeoSRFSx5Qy8f+UM0UJyOu9I1SibJj91z
        gQm+VQo2IfxfFT1jLGKxWh9oqc+a6eQzp3gJNxILVixhmm26ZbueckI/rpvdByG1
        Sb5u1qGYgiZLabDQgir07pY/MY6o3+K7E7NdoqCl08shMXajX5xVDPmyJfjoLWEL
        Nu3nLqOC4upAGHrRQr4ifuFdB/gAkeUs4EJmtShQ131Zd8cn/GdVYAf5i+zYMfAv
        Qn30xSqweA1zsQk+TLeII0GQO4ZOl38REIX41MTI0WaJxSBWRbGja6bCkzwLLrhk
        epPHTrbanU5j0lsAd/NaTqMBgmeud5l/CKEAJAoiFCvFParko6xVHYpDaMmpmcPm
        p3rfBCcyNVBePQF2nW6f7cA/HT6ThOU5SoE04OJxCUTxpIzEnaBoilcD+uRV5k7G
        Dq/ixWnkas+yunevAttlUTOTap9Y3ftv2s7aWDozdOVMIhxQxFAdWDHAaDeYcyev
        qMlF6utFn/ZhWndNvrYNwoR5OAe15c1CVi2rjDkik/MmeekX9nE//ASsPO5GY6+w
        wMmWN0eKBUWmbkprpWkMXZ8IXqDUm0wojYLf2JbWqTtjoDWdQrxbKLtEq3Yu5aEU
        W9QvcXrSkF8hRMEb4VyqNvMPMGo81ikY3C6zgHnt09Q0ZLIXxYHAVGdKAVGVocXS
        XAFoKWWj6kHsd171F/E2CLUam+60dqAsvkQuS6TPlvjAQQ/k1/TPyVkqK6OSygur
        8SorDcr0CseQlOok7yIiRG82p451g6g3b0VFLJkFF15EUe0SzcGX8fUi8mHx
        =D3Y4
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
