apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: staging-qlever
  namespace: staging
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: add
                path: /spec/template/spec/priorityClassName
                value: staging-low
          - target:
              kind: StatefulSet
            patch: |
              - op: add
                path: /spec/template/spec/priorityClassName
                value: staging-low
  chart:
    spec:
      version: "0.1.29"
  values:
    qlever:
      maintenance: false
      image:
        tag: "latest@sha256:826807a37cb369d491ad3bfcb9f6b17ee208352e620e8c146259b8142d791db7"
      data:
        name: mardi-staging
        description: MaRDI Knowledge Graph in Staging
    ingress:
      enabled: true
    updater:
      enabled: true
