apiVersion: v1
kind: Secret
metadata:
  name: prefect-server-postgresql
  namespace: prefect
type: kubernetes.io/basic-auth
data:
  username: ENC[AES256_GCM,data:Z8M9uWDZ2s3nN+v8,iv:U5NIo8iwKia3xDz+hxycuUnGJ7AlHqSDtoPxG6ZZecY=,tag:mDci5YLoWVqY79epO9I0ww==,type:str]
  password: ENC[AES256_GCM,data:ZhgV9PshgNMIB68T1B0vLx/1phuR+qbiZkzzaQBtkLnj/6iW,iv:4fV0vOhzYtB+/smhM9KnCd0bEPdTZ4RjDI9xwn2yHNg=,tag:jpQr4OwqdtlwEsCwGpwXZA==,type:str]
  connection-string: ENC[AES256_GCM,data:BsmwRZThK27iR0FM60Z2DuWb8qIOkUOYQ+ytYuijNq+sEm+LBckJ8YWcqviaSmUn0ADlJZZNhrEnZZontfXUKQxZzvRrRCIm3sOGPdnujTJJzLp5vWr9b4sCESgVuoipmVWhTnZmSBrWFHUD0bchvs9hUr2ebW6D,iv:iUf48Z55OLIEUV9+ndfP4iQfCihs/IE3EpLWle/Fqu0=,tag:OHORUwKNjtB5hEeUQ/Uh1w==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-05T18:36:12Z"
  mac: ENC[AES256_GCM,data:Z8SnvGMIKERAijYAlgtSj0ltIJLLYwSjxUmoAwwgnRbUSEc5ELZxm4qabk3tLY+BiPu3dLuE8iyPx/xQyjNsPsimoret94QhyaqT0ThOQBf0XrHsKt0Lfu8Xyw/q+yOuOX3x4M60GssBB59MYDYmk/oQ2th3c+CDhS52VGqlxnQ=,iv:LDHGYvz7ePGf2rI/3lyl36gouTv3Vno5f4s+IcJ/r+c=,tag:kH321nfH01fm8GnLVGJCWg==,type:str]
  pgp:
    - created_at: "2026-08-05T18:36:12Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ/9HSXqUbFllYv9V0sKzZzHoJdWpYr4n8YkKQOwzYg1Wo2m
        stis2EFulEMPvNAsDqJdkS7SupxxyEs9dV7vCK6lp5yCB+NeWm0pSPl180pA7PW7
        pJXw/h0Ntu2amWr8uhPnz0dPPRnaDu0ieVB1uKhcly4g8G9AleW/fivX5oMpe1ui
        yn+r/2/Ry55pJbU60y6CLKlFwXZ92P2XThOXYwQhh3nsDpWlQiixOSFmzoMqzaPn
        3zZ4+ILok26+b6ixKdYnjEdvlHpY60QtOK+v0GauItIlf0F4oBNyyAh70GOmZl4Q
        N87WgET5cDOPAJgpd6Ipg93V94VXfxkI7BhigVvmvXseD8fUPGz89a3xF/Q4+CHO
        1mztHk+QSAbEF6jUb9DbOfDJxOKcTxHHnHN710US46BD9YF0qtYUVWw324hMUhGf
        zr22ezrR9YVqdaV6MzDAksdhYlwXJfT3UWUwH/ezK3VmVjqFiKSkGym6hVVQ4DEH
        6gXuuE/2V/eXAFQ6RHiuLOU1EexhL60ldHGbDr+sr0TQdpJT38WBGgmITzGKVYUI
        tQW1yFgpBk2B3dmrdGsvtOmBuYAh+6MOs7HxGDkczcUhEQHnj880etDeJpUIc4zD
        L9n6hH93IlNZM5Q6nPT8PHuIsbjI/GWwYQrH2RM/WN2XNwlnE8q4atXah4PFjuTS
        XAFrwLVT7i2BDWPdR+TBeQP+9HOqyCL6zgy9AsdgOAFwk2L4Qd3KydU09lfmL9UU
        ffocYEgBoWYLociA7L+PlLLgFL6F6U7ZLLVN4pZjsDIOLV2vml+lGwBT6kKF
        =asF+
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  version: 3.13.3
