apiVersion: v1
kind: Secret
metadata:
  name: prefect-server-auth
  namespace: prefect
data:
  auth-string: ENC[AES256_GCM,data:EmTkv+p0f9td9ZJLXSs2es96eoySsreVHzPujMrVLl7yhmk4,iv:IwqSMK6e3Ixo17SrmzqyOXLibaCGRs3eaqFvFcbYSjI=,tag:1dkPldfOwk+UWnVEH9TUjA==,type:str]
sops:
  lastmodified: "2026-03-12T13:10:26Z"
  mac: ENC[AES256_GCM,data:ZbK9vqA5JndpNwx+FvOH82THgx3U+JdEJB+fToxwxsn1N5Ugh+uJUtqVRbcWTQnmZ58RDgNEYYdVzIXJmMJG3YdnczF7Y8K8PPTQMwju9MA7tmtz2cL0jU7E//DGXRl4H4Oy3/hG/2qaIJ+tut8SSvhOSsKBINgdvgA7VeGRMJ0=,iv:C2lOxXtI3DeF+7Wxwlo0OoncMXVr7P03y36PSkc82Xo=,tag:nAksccpbzBCjKXyIKtWoxw==,type:str]
  pgp:
    - created_at: "2026-03-12T13:10:26Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ/5AUn8MMLFnuZbLDRRhx1B5ARJd5k2eO27a1Fw1+YvF3zm
        bDSHvgGfIsSg2UzCNrrakgAmMRYG8Oc9wPf/ae8A0uIRI8zVRzQP7emR+JkmlKib
        atjTxfSLGwOsLaw8KXYZXFtiBJb4JaUTjPIiuiZ/pRLAl1eABrroIdVVrzyJH3B0
        cUG+dRdPTvfpfSOepOali/WgzotUNXnS41J9NfF0m+pVTJ49Z3y2H6FMPnacj8cZ
        9k3HD2RjkX4i1iJ5vyMFvCJpxmeopcU9L7X3uWs1Ll07GI03bdwVwUwOYOiO+qAm
        QbK/jIrmzGs4A4xGb7WkRLP6hU5DpU6Gs0O9l8BJQtdm8tgEtq2jxx4v0y2ZOgxM
        5DsjjnPZaJ5PL3O+dNYDSrNs1fd7XFzq5OSZE09ijAY3+LakzGqLF6LnRb30Zbws
        Vx/viVmFI4r7cwdZfijIXwQ9AJDZZp1HS0Z8P31Z0FY7WnHTMK8pT6jMTV6XI4J5
        OBIGI5irhMyK16D22fntFycVrrSApQJMOQSy0grZJMts9fSxHx+/WRPGnOfPZu+C
        pd6eHECpGjDs+oyIVTo95Xz0Zvp1odKfKj860eg0hDU1GHWSCLLt3TzGSbVEGF4Q
        VuIreh8iCEDKPEMi9z1FcurJFLaCXFcoCJXQLfeCq+YwlzCG6jXXnjFQ0PIkvr7S
        XgEPLHcnLQVGbYum0TSJHh0iUWE+G5Q1rrtV0qxEmydz8Tya6G3y/DWKEL7KYbmD
        Nam1dpm2xpdkDmiwKFOsoWZHHgpt18jiCbLebfDRM0cu8Sd22G1ToOQdoZOLFWk=
        =589i
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
