storage:
  className: csi-rbd-sc
  size: 20Gi

admin:
  enabled: false
  hostname: ""
  existingSecret: ipfs-oauth2-proxy
  allowedEmailSecrets: []
  secretRevision: ""
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: v7.15.3
    pullPolicy: IfNotPresent
  cookieExpire: 8h
  cookieRefresh: 1h
  resources: {}
