apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.importer.image.repository }}:{{ .Values.importer.image.tag }}
        imagePullPolicy: {{ .Values.importer.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-accounts
        - secretRef:
            name: {{ .Release.Name }}-secrets
        - configMapRef:
            name: {{ .Release.Name }}-config
        resources:
          requests:
            memory: {{ .Values.importer.resources.requests.memory }}
            cpu: {{ .Values.importer.resources.requests.cpu }}
          limits:
            memory: {{ .Values.importer.resources.limits.memory }}
            cpu: {{ .Values.importer.resources.limits.cpu }}
        
        