apiVersion: v1
kind: Secret
metadata:
  name: importer-secrets
type: Opaque
data:
  IMPORTER_MW_AGENT: ENC[AES256_GCM,data:PAFMZeds0tAwfjqfiuxbwtPjqs8OfgZINcJ/mPNEkLw7RquSz1zP+KoulUyznYJbNzYU/xsE8k/i4d2ciLK5aBvr0k70m5RcZ8pzqXpc+jJli9kX,iv:80BiYpbqNCXHUhU4DMHCHsdJTLrRQZwbFfxnE1QHEQY=,tag:UIgLuRe86P23L+bsDaGwWA==,type:str]
  IMPORTER_DB_PASSWORD: ENC[AES256_GCM,data:obUee7GwIrT2onOPLBD1VafRh1CVMWslE9lkzk9R3NS/Oiqa,iv:yuUOoIXTE27Prigo7XNPjNGpGrLKH39Qvok58IGXEpo=,tag:ztoBX+ZeBb2VYN7FFtzSpQ==,type:str]
  PREFECT_API_AUTH_STRING: ENC[AES256_GCM,data:T3S7sfnQMkG2YyvtoCduDuYhanvRLhtwUmZSwMrNyld41BAl,iv:G00YQUYd11o5WF+HRiFl76pGvaeZ4peEM2ms8/2s0Gc=,tag:mZCQ+Ut0wM/1g36r16wkXQ==,type:str]
sops:
  lastmodified: "2026-04-29T08:07:25Z"
  mac: ENC[AES256_GCM,data:lH+8SQAmFXNpoSyDvIx+R2wX9PzWANl3tBAeaE3SSBx+z0YoBMb1hOcQ9cHeE5THYto75sRD6XYqz45RsdVaAiRjbVar4Vxro8XM7fE5xzlfmaq6u0mmIzNR7btG86xcJmBqTr/DODrJktT8lx+YnOx1FULNtIJbrZUCISVto+g=,iv:7NUADPm339EzLbxxxfpbXnQjpKEy4tWot1OQVE+qGF8=,tag:/Fxwb33K/osCQV8uFIcvnQ==,type:str]
  pgp:
    - created_at: "2026-04-29T08:07:25Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5ARAAovAxxlzkKCRWdyTphUiVMwqFjavPIojI/TNyNQ9Fp5H0
        jqcsCK3E+DoQZncnZBOxAfeQAw1JqbErOo9lnX9XC2IVly4B/KYPtGopi1hwORWp
        nUfmbFGI5gxFdmD32c1mHavuB5K5CBjfJuMHn3tMixXOR5XUoQ4f03pF0WCPv6gN
        N8xG1/kOOQhQX6FpCm90aWLpuI9+n8cUcjJNIJ9cXaOqiRTyxuQljmEdTjcyWdDI
        AxI4rqMdgX2vvfCU+bpBeG1++LpSeVcgh3u+EUsZFCxX34mVs5EM5AlvUUiOUlQu
        SEpdUgHookt13GlqJ+e1qJtOYLB3+mQWnwtEwk4g3KJIwQ7Y2Gct22hnD/MVZbqC
        YoHR0LGFnP81eCFQztUUFJfO+aKgRbEyGWcQqiMUkEwaPYOfoLE2jin7nwj+75pk
        XaGNIajo1y1/AHCvCY7aphwdF8TT7QKJA1SYFnJCHB91sPiCvXACsqv8tkVZD7Ja
        5E6C/CtDt6zNwejG9WP9CcQvZBbV2RDaE1Ads6EdRDcy3Q+dR3d+0k3OFefQT371
        YZXLia1Qyw9SyZeNTR6XDtNRPwT3EcOgRUSpEdTkGYqoHeEWyOHt7eziv+64n53U
        uTLguIP20PDVi+Ft949IHkur26ENSo5dHCrQpRs/F3yg0edrK0v1h90ocRLBDljS
        XgFVA7Xjl9vCHAzRW1tz+5VGOiv2Odb2oEqbR/hdZFywcQRRfW7fWN6c6szy/TSX
        aGLrFbs4mRttuuhn7sepQfa5dh1SyVpULhC2PnKiYHnrMH0viZmu51kxHukbAaI=
        =P6FN
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
