apiVersion: v1
kind: Secret
metadata:
  name: importer-secrets
type: Opaque
data:
  IMPORTER_MW_AGENT: ENC[AES256_GCM,data:IemllKLcbIPD57XGYGpT7oZv0mPCNYSxY+yRDZar/zNBp6qC+lqtg8osBBU3F+MznsLf3Q/V2yciDe4Gn4MfwGSjcSxZVTiu0Qs2+uuqmVO08z0P,iv:8JXIT71O4hRSgpiv+HTHPnMpUrjVv6b4iaS0ZkkY4qw=,tag:GfFUdkyLNbv1XCjIZQHYsw==,type:str]
  IMPORTER_DB_PASS: ENC[AES256_GCM,data:o4IBIcz4WPW110u3HZb0Q5Y9paRc/C9AziUfoG5oZt0LFpQt,iv:uPXlM3F9O2ZC3dHkr5W9R7Qj1xOPJymTU9AVLhCeFNg=,tag:1Sff/mCczM9NinslXkYQWA==,type:str]
  PREFECT_API_AUTH_STRING: ENC[AES256_GCM,data:3FwZZZa50lFrphyZsNXlfsEybSsukYL7YD7JYPnlIGeQduDo,iv:Qnrbth4wxsOUB2yXK4nW0Bp2VmjXAqJ5jGBjk7Aoskc=,tag:AwIVcNAW6hkWuZbGox8jVA==,type:str]
sops:
  lastmodified: "2026-03-12T12:42:48Z"
  mac: ENC[AES256_GCM,data:E+bw8ImILoE6RLSXNLlxZXcswoi7cISDQrosKyVlKZdgXJW3SfCnsDRIrEPcC7/bTNCWoqGyjaN+oXQ3TbBKc0WiQzvYLaqMIA0wiBfj5S2XFVXLdwz+ZhRAoG3MSfoOjSzZhi3crM5X01ZvYKKIO9W8x6brZeAqCwJJOGxNokw=,iv:Af+l8Ltmc306c2JvODv6+28avrencHG9wkfblp1XGjM=,tag:TdXQcrp7oAwMH/3GWsUy0Q==,type:str]
  pgp:
    - created_at: "2026-03-12T12:42:48Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5ARAAlLNkvjFlaLmcdoH75Y8MDudv/tYehzsmihABC3eFImBf
        FjPSxn+hSJrfc+OVMbyhet9+2Jgd/EpeYeX23gx8amYQ5vjRE4LFPZgRV9T8SJeO
        AWqgaix3NVgeBLWqCTAPNWqLTloO+3PotrfZn5ZvEk+0sKRFj4PnNo3YG7Mj3pxL
        Em86Dews4R3WOdJwm/Lm1cfJ4AJAg+Mp75vdz/zMalUAIiO07VvyDSRC6Dz841jG
        RfiZrb5nwiXJ5IVpOCTMxHS/uJBzy5IkxuBiKlWtNTtwFntF5bLFB1+JqP/0vvuI
        +8LUo3+X20ON6BSce81LYxursbuu0ErGi7eZfpKRXEhcbqFNPzryCHY4ZCN4709g
        FYv+sN1pMnxuShg+ykAsZwdJkNG5FV+JC44JSmoAx29FxEGN0M4DkhwjTah7vTOx
        yDVVIO2vFK95D4Df5StYvNAMMZYuGWT19/A5UBCatmF+aSMC5Oz+NtLlq93Ur3/b
        tyngHQUJZce4QMUN/T7UDqYeX58LApdVwztn23OGQFiQ6lCUm/dYT714kLBl5tum
        7annq6cyFY3eBLxmJn+7s6RNvEdVGYYNxQw5wOH+/9TbTGhfUiGbbxJvWFqKRIE4
        Yh8GuYUazC7Z3tEn9xqgMbIZDuZW+zR8TA1/lAUmaF6CXERJEQHa/kLdD5E24zDS
        XgHBSs/nBWYBSA33jGJM+GLOstnpRh+BhirU2Go+x3sLNnEPfHtrwVEYWeBfxkFI
        feLVvkw8kfaWhhHN8YW/A9jlQtwBM8QXmVJIPBbYs6uuA3MqZo5X7XGrHRFYDnY=
        =SkKp
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
