apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  labels:
    # Match the label selector used by the kube-prometheus Prometheus instance
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: kafka-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics