apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: staging-doip
  namespace: staging
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: add
                path: /spec/template/spec/priorityClassName
                value: staging-low
  chart:
    spec:
      version: "0.1.4"
  values:
    lakefs:
      url: "lake-bioinfmed.zib.de"
      repo: "sandbox"
    importer:
      url: "http://importer.production.svc.cluster.local"
    doipConfig:
      ports:
        - name: stg-doip-tls1
          port: 3567
          tlsPassthrough: true
        - name: stg-doip-tls2
          port: 3568
          tlsPassthrough: true

