apiVersion: v1
kind: Secret
metadata:
  name: wikibase-env-secrets
data:
  MW_ADMIN_NAME: ENC[AES256_GCM,data:u7e0rAnzS1w=,iv:DRQ1yGJcZZgaXaJYFCMnCpjQLIOr7FLPE20nMKnK8fk=,tag:wJreCiYD/40aJthVfaJ3Kw==,type:str]
  MW_ADMIN_EMAIL: ENC[AES256_GCM,data:XdxsFeHhixMpENpe97vnIlWp2lj41Yd7,iv:r7DNgHfGk3VV8Bbt9i/2obvefON9L+7SnFSKOMaBTrE=,tag:CAPPDHUWs970K7jX1aM4lw==,type:str]
  MW_ADMIN_PASS: ENC[AES256_GCM,data:XU72oP4oGE3Tevkw0+rxTaOgdjGNSdCAUReT3A==,iv:J99uKfJWSyi+z2qUQmdxjTMlTqJLfzgd7LpkG7kqsh0=,tag:IwAkEh9TeQRWv1mJzjqjBA==,type:str]
  MW_WG_SECRET_KEY: ENC[AES256_GCM,data:A8cvFuSy2dZ3OkuslMXYF6GbhhLPfqzkVKavAA==,iv:de8ycOBuId0z4Y2oyuMBM0EMUOttpZUstIXZHadv4zg=,tag:mkHwZTMRytwmdl++uCvlAQ==,type:str]
  POSTGRESQL_USER: ENC[AES256_GCM,data:fHdKXKVu9BY=,iv:Lp7BP76MvbaByGHqMs27lPBcNLhAF7BUcx3XymCFNik=,tag:EWa5384kPOhplcpK3XCr/Q==,type:str]
  POSTGRESQL_PW: ENC[AES256_GCM,data:7X4t4Y35kJF/2JlaE7IKV+t0415dywH6Ll6jOhJymLimBy39,iv:s1RCQOhkUHzjhJsNWE0vADgHknpPxOzKF9bf3pNaTl0=,tag:RVp6jLrLVXOFGKkyY1t4lA==,type:str]
  SWH_TOKEN: ENC[AES256_GCM,data:Xpz2Cw7OrlrkWUaeNZsfMpXlfPlfOtVuzZ15IrriqDfS0MbPPb6845HjTGY3c+z/7DaC1WPD2iOtQBhHYVDEBO0UOw+fKMn9eCx9/AWPCmkWd3Bv0zIKGXRk4d5l1341wGnRWEUoA4ULIkv/F8l82GeaFSMOMjYcsmxArMzfoPxrK0j2rSazV3XZUs5Uj3n0yHJcOVK6Uvd1g3vEZ6zyriKXDEX87EpHZXSZYphXvaqmDk/gzJNqtvzYEGbAcMbQuz8ReUGsHWi65IU3P1U13OPIMItz2UZwmpXMXlqKCXV/ErIVAohZikvLffhnUqHPkMEVZaHaCOrByXGt++8wuzv18Q8v6cZ8pEkQ8fap6w3M1Cec15kpBKVjj8kutnSPm9lrCw0hn7l+ubBbmZKnOhh/7pB09/Og4XPAqO64vh5IJnZ774NoUXPpxKvRKSk8RMmZpm50TnzE1qFmcf0aj8fr+KNC9JwjELjz2lOahHY8xBKQ3NPLP9707wGm1j+xvbQHLfUWLfZQOdDALkPRaAmV4Luw6gexoxXPRV5MlQcMuhoo/QOVSquDAU66znJL+qoF1ZHIeq+QCzr8b97JCoYuRMpUCgYEQY3AP1KUfqe9H3pAN+CuSvzK+hzsO35jDdSS7Q+xvMkLZ+ApUSrLyoqLX5/WsLQG5O4Trl8jQ6U4Pbwck7DDqoSH5uiOuVHiEnQ0FjShcERdmHzHUQ+7UUcvsYlAYGwWJURgqbao7CcB5nbyqkxPqrWfcha3AKwYHg1GZpNdIPdR8rf/s/chcDne9dBf7uT4h+dQapFpGxT1eEOTIUJESFUZlHDsZ69ByqZ/qZfSmMHV9gM39oSlbCKkYUp1wCxYQCmulVhL7ITZjrTMSnBks9H/5i8NsXohCLWplGo60OWqLTMDTw5+mJHbiKVjqhkgpdLva7KTuajqMNiQK37BF5LmAPEeHnSzy0uxHkaSOUxgd4HrmPfjigNG9jfPIFO6UJG28uKcrP2axQxAtto/+5Xrmu+/LrZj6Afb7d5UuF163lTObXnDs3iOCfUGKg2e6mt3/BGYLuAb32TacLX3Tx2XVi2Wy0CMQ3B0ae5YcDvRcBo9S4pWcLSUGK9Y9HNNhrBaA1Z4J1Fo5EyoP3LBkTP87VoBJT9MhIdGbdqlIzprIPb9KVu6xQ==,iv:21ME9M7wtmamMYwiLM6mPtAJBqgq5reI5kVQG7spxq4=,tag:E8aLL/yMBXPCQTBkOuaa/w==,type:str]
  SMTP_EMAIL: ENC[AES256_GCM,data:/nS9/RYbyA/FRlsuYL3yYATJuOKI4xx6k0gR7A==,iv:I+07upNAUDaks3aAICK7B2q8itFn9PH8rVtk7mnuDTg=,tag:T/YlP82TyKhRoUI3iquELQ==,type:str]
  SMTP_PW: ENC[AES256_GCM,data:tm12n09U29vzTNBm0NrZ5gc9SG7SQGKa,iv:UQ00GW4dWtm4CBnbm1wqQb+28Dw17xDFDC5caWKQQAc=,tag:JHV4ZNCZ8wQk8hIl9SbXLw==,type:str]
  MATOMO_TOKEN: ENC[AES256_GCM,data:LGZgamOV/1Z71dxJl2nCoqI+Y1q+sBwPOks+uPh7ifTtVPig67cRfpXmoVE=,iv:fcrl2MmRFTWLOUo4OC9kbZc8BbUVszDKYew0EgQeiec=,tag:aITYa2qcwnJoJb8NR8W4lA==,type:str]
  NFDI_CLIENT_ID: ENC[AES256_GCM,data:zjxolkQdd3NMe9BCC/reIJaBkAKZJ4Mk,iv:lvgtoEv/2kS5zN3M9U4x9Pht9iyUKJHbV1HmMf5hbBI=,tag:5ZJikRr71M2XSkdMcB5Qrg==,type:str]
  NFDI_AAI_SECRET: ENC[AES256_GCM,data:mx2CdnGSfM1tIBraB1ajZYk4VghwPexZ,iv:+NGT1T0i7ETaxg4MCt8UxsGy6i2RMhKvJFO018J7IMk=,tag:4w9s/+hWj6KR0fADPAC+aA==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:/TmsfON6SZ4pJ9iHhvvTrew5A4M=,iv:nEVvSuYBH3sH5T244ca+nccbYagd0Xv0/lgZ8VjSapM=,tag:i6Z7LpdpsiCMrvKutgDwfQ==,type:str]
  S3_IMAGES_KEY: ENC[AES256_GCM,data:7EbEPE5LrHpj1uthB9HgX76xrx/h+Uzf3HpJRw==,iv:S/MdppPYG0tUSNbymR+3tDrwchYgkikkOxMwmxQirGo=,tag:uUNyFoemYCB3NA8ktAvIcQ==,type:str]
  S3_IMAGES_SECRET: ENC[AES256_GCM,data:UveoRurYh/C6Psx/dJh9dirwyglwPkO20kiq014T4u7EKjtcKJn6dt0/N+Cf0rf3vRGm4yAIp/8=,iv:Bq+v9VBtSZR0Cke0YHzvatg0ZoD1iGx4UEO5U89IGOo=,tag:KfpkHr9LrbDej+ZrJB21Kg==,type:str]
  S3_ENVIRONMENT: ENC[AES256_GCM,data:WuyQsZ3Qc6U=,iv:LJYshJ6t5gb3KnO/NqvO8fXV8nfEIY0xaf6RyO71GDA=,tag:QP6HoI8oeFMCuU0jzOqRiw==,type:str]
  MSC_PASS: ENC[AES256_GCM,data:CDl9/FuD/CSrk0cVqXxKWl2eBSZAsKB/xEQDucipewXKgmwL,iv:g2a4JEHfyLx0pz4gkt7pjYo0iSx2SJgSo332EUY6/mE=,tag:jarodFpBBLT5X0vRZmoPBA==,type:str]
  ABSTRACT_PASS: ENC[AES256_GCM,data:6QfpuHdQKmvTBLYyH5iKOigSTod/TC75JCJyevPgza3tM7y3,iv:/uIzDFXV0tZAZ/QncI5frKXXGqvres/dNSEaujHtiyE=,tag:21hdI/SMCk7k8Uq+QiHvCg==,type:str]
sops:
  lastmodified: "2026-03-24T08:46:19Z"
  mac: ENC[AES256_GCM,data:JjCpmFflK3mhzJ4+rraSZAzrWA2rAtqeX3rBbsoUSWwmWOvSlDV8U/iVPba1FIUTUiXB2JRbI68D8t+DoS/BggbubLsPJmwNHZyOcEOSq8HilInHVRxAzjqUuNnyuPJrKO8SVS0pNPKShMqFSmLOtZYzgEty1pqGqeld4HB3KDE=,iv:VXC/wqrKUOzc38QzYuP+34NZd8z1jEYASX5L+m8kklE=,tag:VQCSabczrJvBpyRpDXyVZg==,type:str]
  pgp:
    - created_at: "2026-03-24T08:46:19Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5ARAA0DwEPiqwyZdyRLHsl/bvVjFqmcR2/O9LqcRwldF8kWMY
        ziO3HjY8FADzo0TGSZLrppWab0ZNBfbJlMZe91YHlIXNU0TOWwTfCd3SOwSt5dYc
        STho7Zv/OnuIxFzo44Pv+C9fo3X3gW9QLXS3Frr3Pw8CHAsKyCdyyFP2kRbi7If1
        xfh7I4E6llLhUqsH9ZNBUgKDx7OOn8igAKKnoVjuAo5zlGBz2KZNTs7VHNC1BrmV
        vYd1oYAUF51McnVv2UvC0vzpFZ3U/pRV40cSxYSarGpr0JrpN3OxdCt6DASQUQ6K
        P9RWoSQrqL6WleokSZGfNWiprvXePLnHKL+bKXdsY3TvEarYilJ/srUcVMnKzuJ5
        fPcDdIc4FfMWd6xbyXQQtBxRf3UTHKQTPxRNZo8NJPx0fyTnKhtLWlmbhc3l+vWH
        OapsNgbfwilZxwmcfs1G55Og89KHxdjVwIjT2spEzCTQu/lFWS85MnuCH8dqVz1C
        FFG5JsYQ/q8nYWptaWlCmfTidfkzXtR3dgwA+k6QZcMSBZK9bYvkpNL1AwmoLNd4
        EguD1MgWOvOtCNOKdggPxqkKfFC/aiIVSBAUFyf4+brziFfiM+MViWeWkRC8YHH9
        QS+zOBcXk49+2MHNywGy5NrC7oyQA84xzsSYvlic/sk5Csbp43xU1XeSRQUL/LvS
        XgHaHeTGNYlalZklbL5LrN3b8tJwV3yIi7/1Sr2rm+B6/k54/wyXY2Y30nDQ6DFU
        I0wMJRih9WRksknRd8lpEtidh/WFP2WZlWuGKu+uOzOs1eSRsz1Oy0Is19XeVtc=
        =bdoa
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
