apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - grafana-dashboards
  - helm
  - keel
  - mariadb
  - portainer
  - postgresql
  - prefect
  - priority-classes
  #- crowdsec
