{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-strip-sparql
spec:
  stripPrefix:
    prefixes:
      - /sparql
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.subdomain }}.{{ .Values.global.baseDomain }}`) && PathPrefix(`/sparql`)
      kind: Rule
      priority: 10
      services:
        - name: {{ .Release.Name }}-readonly-proxy
          port: 8080
      middlewares:
        - name: {{ .Release.Name }}-strip-sparql
    - match: Host(`{{ .Values.ingress.subdomain }}.{{ .Values.global.baseDomain }}`)
      kind: Rule
      priority: 1
      services:
        - name: {{ .Release.Name }}-ui
          port: {{ .Values.frontend.port }}
  tls:
    secretName: {{ .Release.Name }}-tls
{{- end }}