apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.qlever.port }}
      targetPort: {{ .Values.qlever.port }}
  selector:
    app: {{ .Release.Name }}
