{{- if .Values.qlever.server.enableMetrics }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      authorization:
        type: Bearer
        credentials:
          name: {{ .Release.Name }}-secrets
          key: TOKEN
{{- end }}
