apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.qlever.image.repository }}:{{ .Values.qlever.image.tag }}"
          workingDir: /data
          command: ["/bin/bash", "-c"]
          args:
            - {{ printf "sudo userdel ubuntu 2>/dev/null || true; exec /qlever/docker-entrypoint.sh %s" .Values.qlever.cmdString | quote }}
          env:
            - name: UID
              value: "1000"
            - name: GID
              value: "1000"
          volumeMounts:
            - name: qlever-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: qlever-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "csi-rbd-sc"
        resources:
          requests:
            storage: {{ .Values.qlever.storage }}
