mediawiki:
  image:
    repository: ghcr.io/mardi4nfdi/wikibase-staging
    tag: latest
    pullPolicy: Always
  replicas: 1
  port: 9000
  scheme: https
  db_server: mariadb
  db_name: my_wiki
  db_user: sqluser
  db_primary: mariadb-0
  db_secondary: mariadb-1
  elasticsearch_host: elasticsearch
  elasticsearch_port: 9200
  redis_host: redis-master
  redis_port: 6379
  memcached_host: memcached
  memcached_port: 11211
  latexml_host: latexml
  latexml_port: 80
  formulasearch_host: formulasearch
  formulasearch_port: 1985
  phpfpm:
    pm: dynamic
    maxChildren: 75
    startServers: 25
    minSpareServers: 10
    maxSpareServers: 40
    maxRequests: 1000
    requestTimeout: "60s"
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

apache:
  image:
    repository: ghcr.io/mardi4nfdi/apache
    tag: latest
    pullPolicy: Always
  port: 80
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

jobrunner:
  replicas: 1
  apache:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  mediawiki:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2
        memory: 2Gi
  phpfpm:
    pm: static
    maxChildren: 5
    maxRequests: 500
    requestTimeout: 300s
    startServers: 0
    minSpareServers: 0
    maxSpareServers: 0

varnish:
  enabled: false
  fullnameOverride: "varnish"
  backendFirstByteTimeout: "600s"
  backendBetweenBytesTimeout: "600s"
  purgeAcl: "10.0.0.0/8"
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

blockHeaders:
  enabled: false
fail2ban:
  enabled: false
  denylist: []
secrets:
  mariadb: mariadb-secrets