apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: staging
spec:
  chart:
    spec:
      version: "0.1.8"
  values:
    replicaCount: 1
    replicationFactor: 1
    minIsr: 1
    numPartitions: 1
    antiAffinity: "soft"